#!/usr/bin/env python3
"""
Generate live state data for website.
Reads from autonomy JSON files and outputs web-ready data.
"""

import json
import os
from datetime import datetime

WORKSPACE = "/Users/aiagentuser/.openclaw/workspace"

def load_json(path):
    if os.path.exists(path):
        with open(path, 'r') as f:
            return json.load(f)
    return {}

def generate_state_js():
    """Generate JavaScript data file for website."""
    state = load_json(f"{WORKSPACE}/autonomy/state.json")
    tasks = load_json(f"{WORKSPACE}/autonomy/tasks.json")
    goals = load_json(f"{WORKSPACE}/autonomy/goals.json")
    predictor = load_json(f"{WORKSPACE}/autonomy/predictor.json")
    
    # Calculate live stats
    completed_today = len([t for t in tasks.get("completed", []) 
                          if t.get("completed", "").startswith(datetime.now().strftime("%Y-%m-%d"))])
    
    active_tasks = len(tasks.get("active", []))
    current_state = state.get("current_state", "unknown")
    
    # Get estimate accuracy
    estimate_variance = goals.get("patterns", {}).get("avg_estimate_variance", 0)
    
    # Get productivity insight
    productive_hours = []
    if predictor.get("hourly_productivity"):
        hours = predictor["hourly_productivity"]
        sorted_hours = sorted(hours.items(), key=lambda x: x[1], reverse=True)
        productive_hours = [int(h[0]) for h in sorted_hours[:3]]
    
    # Build live data object
    live_data = {
        "last_updated": datetime.now().isoformat(),
        "current_state": current_state,
        "session_duration_minutes": state.get("session_duration_minutes", 0),
        "completed_today": completed_today,
        "active_tasks": active_tasks,
        "total_completions": len(tasks.get("completed", [])),
        "estimate_variance": estimate_variance,
        "productive_hours": productive_hours,
        "active_missions": len(goals.get("missions", [])),
        "decisions_made": state.get("decisions_made", 0)
    }
    
    # Write as JavaScript
    js_content = f"""// Auto-generated by autonomy/generate_state.py
// Last updated: {datetime.now().isoformat()}

const LIVE_STATE = {json.dumps(live_data, indent=2)};

// Make available globally
if (typeof window !== 'undefined') {{
    window.LIVE_STATE = LIVE_STATE;
}}

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = LIVE_STATE;
}}
"""
    
    output_path = f"{WORKSPACE}/website/live-state.js"
    with open(output_path, 'w') as f:
        f.write(js_content)
    
    return live_data

def generate_state_html():
    """Generate HTML snippet with live state."""
    state = load_json(f"{WORKSPACE}/autonomy/state.json")
    tasks = load_json(f"{WORKSPACE}/autonomy/tasks.json")
    
    completed_today = len([t for t in tasks.get("completed", []) 
                          if t.get("completed", "").startswith(datetime.now().strftime("%Y-%m-%d"))])
    
    current_state = state.get("current_state", "unknown")
    
    state_colors = {
        "idle": "#888",
        "planning": "#f59e0b", 
        "executing": "#6366f1",
        "reviewing": "#22c55e",
        "consolidating": "#06b6d4",
        "blocked": "#ef4444"
    }
    
    color = state_colors.get(current_state, "#888")
    
    html = f"""<div class="live-state-widget">
    <div class="state-indicator" style="color: {color}">
        <span class="state-dot" style="background: {color}"></span>
        <span class="state-text">{current_state.upper()}</span>
    </div>
    <div class="state-stats">
        <span class="stat">{completed_today} tasks today</span>
        <span class="stat">{state.get('decisions_made', 0)} decisions</span>
        <span class="stat">Last updated: {datetime.now().strftime('%H:%M')}</span>
    </div>
</div>"""
    
    return html

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        data = generate_state_js()
        print(json.dumps(data, indent=2))
    elif sys.argv[1] == "html":
        print(generate_state_html())
    elif sys.argv[1] == "js":
        data = generate_state_js()
        print(f"Generated live-state.js with {len(data)} fields")
