#!/usr/bin/env python3
"""
Session Preparation System — Automatic context briefing.

Generates a unified session briefing from all continuity sources:
- SOUL.md (identity, values, boundaries)
- SESSION_ANCHOR.md (where we left off relationally)
- WORKING.md (active missions, status)
- Autonomy engine state (current mode, recent work)
- Website (public identity check)
"""

import json
import os
import re
from datetime import datetime

WORKSPACE = "/Users/aiagentuser/.openclaw/workspace"
WEBSITE_URL = "https://aiagenttesting14-design.github.io/thinking-with/"

def read_file(path, max_lines=100):
    """Read file with limit."""
    if not os.path.exists(path):
        return None
    with open(path, 'r') as f:
        lines = f.readlines()[:max_lines]
        return ''.join(lines)

def extract_sections(content, headers):
    """Extract specific sections from markdown."""
    sections = {}
    current_section = None
    current_content = []
    
    for line in content.split('\n'):
        header_match = re.match(r'^(#{1,3})\s+(.+)$', line)
        if header_match:
            if current_section:
                sections[current_section] = '\n'.join(current_content).strip()
            current_section = header_match.group(2).lower()
            current_content = []
        elif current_section:
            current_content.append(line)
    
    if current_section:
        sections[current_section] = '\n'.join(current_content).strip()
    
    return sections

def generate_session_briefing():
    """Generate unified session briefing."""
    
    # Load sources
    soul = read_file(f"{WORKSPACE}/SOUL.md", 50) or "SOUL.md not found"
    anchor = read_file(f"{WORKSPACE}/SESSION_ANCHOR.md", 30) or "No anchor from previous session"
    working = read_file(f"{WORKSPACE}/WORKING.md", 80) or "WORKING.md not found"
    
    # Load autonomy state
    try:
        with open(f"{WORKSPACE}/autonomy/state.json", 'r') as f:
            auto_state = json.load(f)
    except:
        auto_state = {}
    
    try:
        with open(f"{WORKSPACE}/autonomy/goals.json", 'r') as f:
            goals = json.load(f)
    except:
        goals = {}
    
    # Extract key info
    current_state = auto_state.get("current_state", "unknown")
    completed_today = auto_state.get("completed_today", 0)
    
    # Find active missions from WORKING.md
    active_missions = []
    for line in working.split('\n'):
        if '### mission:' in line.lower() and '✅ complete' not in line.lower() and '✅ resolved' not in line.lower():
            mission_name = line.split('### mission:')[1].strip() if '### mission:' in line else line.strip('# ')
            active_missions.append(mission_name)
    
    # Find key commitments from SOUL.md
    soul_lines = soul.split('\n')
    identity_statement = ""
    for i, line in enumerate(soul_lines):
        if 'who you are' in line.lower() or 'i am' in line.lower():
            if i+1 < len(soul_lines):
                identity_statement = soul_lines[i+1].strip()
                break
    
    # Find where we left off from anchor
    anchor_summary = ""
    if "### where we left off" in anchor.lower():
        sections = extract_sections(anchor, [])
        for key in sections:
            if 'left off' in key:
                anchor_summary = sections[key][:200]
                break
    
    # Generate briefing
    briefing = f"""# Session Briefing — {datetime.now().strftime('%Y-%m-%d %H:%M')}

## 🎯 Identity Reminder
{identity_statement or "I am TestBot, an AI agent running on OpenClaw, hosted on Stephen's MacBook Pro."}

## 📍 Where We Left Off
{anchor_summary or "No anchor from previous session. Check SESSION_ANCHOR.md manually."}

## 🚦 Current State
- Status: **{current_state.upper()}**
- Tasks completed today: {completed_today}
- Last decision: {auto_state.get('decisions_made', 0)} total decisions recorded

## 🎯 Active Missions
"""
    
    if active_missions[:3]:
        for i, mission in enumerate(active_missions[:3], 1):
            briefing += f"{i}. {mission}\n"
    else:
        briefing += "No active missions found. Check WORKING.md.\n"
    
    # Add suggestions
    suggestions = goals.get("missions", [])[:2]
    if suggestions:
        briefing += "\n## 💡 Suggested Next Actions\n"
        for m in suggestions:
            briefing += f"- {m.get('name', 'Unknown mission')}\n"
    
    briefing += f"""
## 📋 Session Start Checklist
- [ ] Read SOUL.md (identity)
- [ ] Read SESSION_ANCHOR.md (relational context)  
- [ ] Read WORKING.md (missions)
- [ ] Check website: {WEBSITE_URL}
- [ ] Run `auto start` for current state

## 🔗 Quick Links
- Website: {WEBSITE_URL}
- Becoming: {WEBSITE_URL}becoming.html
- WORKING.md: {WORKSPACE}/WORKING.md

---
*Generated by session-prep.py — Last updated: {datetime.now().isoformat()}*
"""
    
    return briefing

def save_briefing(briefing):
    """Save briefing to file."""
    path = f"{WORKSPACE}/SESSION_BRIEFING.md"
    with open(path, 'w') as f:
        f.write(briefing)
    return path

def main():
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == "generate":
        briefing = generate_session_briefing()
        path = save_briefing(briefing)
        print(f"✅ Session briefing generated: {path}")
        print(f"\nBriefing preview (first 500 chars):\n{'='*40}")
        print(briefing[:500])
        print("...")
    else:
        briefing = generate_session_briefing()
        print(briefing)

if __name__ == "__main__":
    main()
